#datasource:
#  url: jdbc:mysql://localhost:3306/spring6?useSSL=false
#  username: root
#  password: 123456
#  driver-class-name: com.mysql.cj.jdbc.Driver
animal:
  cat:
    name: tom
    age: 18

person:
  xueqian:
    name: xueqian22
    age: 35