spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring6?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 10086

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:10086/eureka/


