spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring6?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#  freemarker:
#    template-loader-path: classpath:/templates/
#    prefer-file-system-access: false
server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
#    registerWithEureka: false
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


